sudo: required
services:
- docker
language: node_js
env:
  matrix:
  - PROVIDER=google
  - PROVIDER=aws
  - PROVIDER=azure
  - PROVIDER=openwhisk
  global:
  - azureSubId=09f8875a-6349-4bad-aa48-290ee9895861
  - azureServicePrincipalTenantId=33ece144-e0a8-4c38-982c-ad40d89eafd1
  - azureServicePrincipalClientId=acf06957-006f-4635-abe5-b9ff835fec06
  - secure: BIdG+UHLzL5UFpxRsMVp9ZdVMnRwEZH3XUrq1cNClN7ZovmQL4m0Ph3KDO+M3njZn+Nh4qmpIehl/w/2f5MqPgOa7+dKtb62q8647/OVJKMIHd1XDCfZ7KozVgw1ZVRT/IabOQ0hEgtgiJK0ITa9p1c1NQO2U77LRKUawOYoVAGeyQW3EXiQp9S5Yt2qhapzI8kSEI+w2PcU5UF3u1+G0p2EFgls+6k6dsOcXMDHQVCzF9+tDr6V9eH+OgzS3KgdDA+Qs2+TzvwYAB0ftnlKptFe/AfMMIsbGa2erlnBefVpYwKvlq/CKrmh8WwpC6xpUI/U4pRbrkyvBegCOnTfl7D6t1QPojI2X+iQjyA2ylp1nxUw4YwEejtAKPp7YMpX3Fnve9R300azOQHAhj+lvNipfzYPz2om3YpYBJyFCshJr5pK8tycSNqRzyjohZEO8F0dNXOjQ8SFECmyJ1KijFxGKq6Kd+v892NAc6NkvE65ogFiQmLxtYKfvXDBCIzoDikm9H1TxDfmL1XiuXrgDMOT5RbFca5t0xs60v9nrUlQbSVyJnO3R2I9JH7EJ3tiwnk9I7jQNmUIrDKY7FB3mcV0zKTSX0JTT7rR46Ok0Z4F5wKNkfnMn76EbYEnGiOYOtjh3wP4uaRieD/uuyw0xj9OmsyR4JuGCN9lKih4Xiw=
  - AWS_IAM_ROLE=arn:aws:iam::524374011118:role/lambdaRole
  - AWS_REGION=eu-west-1
  - AWS_ACCESS_KEY_ID=AKIAIU77AXAV2UQECR3A
  - secure: svlP12fiW72UFlU9pvY2XkFawWzhbLW8+AO917HeExIrx052GqNiND0b44Igminj0USyoayky52RZfGvmNXA8MJ5G+QCUg5baYQf0OudyRFVL0PZqyM5TX3VoDr3QEyGNLITRN/mO3FMR9YCpnF+d8aI2sZp+udA3yE+3Xw5RWgcKS9SM1WjFXC6sJbKBS4WVdvdDxl9GYnG7x8IwNNMcHk3k3xZQgt45x4qvVweSA1gmREBgW9BsJ1vJdy+2RY5UsOmoL7Grwms6YrS+QvaLUnb0ctVP8pAMsnAdAXf/LlDA52Lo2uXJPPURl+utQt3Syw/MExs+f5qC5KQ0gATRsxNmHbLVAdojzZ/SjAYzvjhAHmjNQL3PcxfhXmvu6OcrAPnsIkwQgyXRbcvIHX0T+iZJVO8U8TXzrW0sbY6EHdOwfF9ABJ1Gf9as6GWeATkbXAHi/rCQh4alfifGDL7jwbDg1ZzUdzVuTXg9XDIHzUxJ+icj44BHNbe3SBBmipPJWJPO71NneAC8AeiWbYlyWy387eIxgp5eaRcm1G6QTAIbIzkSolu+9RofXhIXoC7vw+oBj7r2lkWvfRLXBQ2dGyiW+F2EkcFMuY9zMAZuVnFm3HVeFPUaa72tP4y2IZSXrYqumSZ92wYEJGI96toOV4CFub1Sf0oS3t5zbnXxWY=
  - OW_APIHOST=openwhisk.ng.bluemix.net
  - secure: ayxbxNRXwQtpxVEuNj2B1J6ASl4Y9qAFme7qcBGyKXx/0XITlDP7In43dGyFXfFXJ/gK1PgmsjdzYZUEmFjkJbA2n1hdjz4B2VqX6+4VayKFcNzggwKRoqZtllAqVo/eBx5WUvTpiLcU4SxwLZfBYqh95tlb/MISgtHaYhcXWmkQPTGygIrPP9ySqIH649UpF3KPldHayjROnpeJjP5o0yzQwPjfPuIL2wx3VZ+gZBEBytP+k1gbZdKAXO+nwppV4DMyKLVfCngX2kFWgezZFtDOQHybYLZXsGKkhSckwlTEwCk8zuRWK0Kc8yyhHCF2CI56cENswV80Pg6HDTmNS0IwmPN1dncGAQVa1jQTF+3v9Cm/7RaN2CCfGRX4NHAsBZCSd/d4i54mmxhSL9nhNkAOuWJsS7xcPgPjd5ljz1qo6kIUyrVj7S/kClrQ0AjE3k+ZhWEeRDMeOiSjafmsBTiv48enUZZSPIOWFBk+kZT2lQeACx/QiMSbelAqL2Mcjid9sqx61LaM9f8FoC1hgo/nJc1MEcxaerGtWY5iERtftLklal2IOJbTxXxbCtRAGW+mSx8RPAyVcgWHLenSmXRh//m2VIxxXQvHiQW0F3QXOClIKYpxGp8vFpUGXVzKdTDtzuZIGPbWSh8zeXg4AOkHs7jCjlFwK2gfD3HmpY0=
before_install:
- npm install -g serverless
- openssl aes-256-cbc -K $encrypted_d7975d884fb5_key -iv $encrypted_d7975d884fb5_iv
  -in google/keyfile.json.enc -out google/keyfile.json -d
script:
- cd $provider
- npm install
- serverless deploy
