service: ${env:AWS_SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: eu-west-1
  timeout: 240

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - { "Ref" : "RandomBucket" }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${env:S3_FILES_BUCKET_NAME}
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "RandomBucket"
            - "/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${env:S3_FILES_BUCKET_NAME}
            - "/*"

  environment:
    BUCKET_NAME: { "Ref" : "RandomBucket" }
    FILES_BUCKET_NAME: ${env:S3_FILES_BUCKET_NAME}

functions:
  hello-128:
    handler: handler.hello128
    memorySize: 128
    environment:
      MEMORY: 128
    events:
      - http:
          path: hello-128
          method: post
  hello-256:
    handler: handler.hello
    memorySize: 256
    environment:
      MEMORY: 256
    events:
      - http:
          path: hello-256
          method: post
  hello-512:
    handler: handler.hello
    memorySize: 512
    environment:
      MEMORY: 512
    events:
      - http:
          path: hello-512
          method: post
  hello-1024:
    handler: handler.hello
    memorySize: 1024
    environment:
      MEMORY: 1024
    events:
      - http:
          path: hello-1024
          method: post
  hello-1536:
    handler: handler.hello
    memorySize: 1536
    environment:
      MEMORY: 1536
    events:
      - http:
          path: hello-1536
          method: post

resources:
  Resources:
    RandomBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET_NAME}
        AccessControl: BucketOwnerFullControl
