service: ${env:AWS_SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: eu-west-1
  timeout: 240

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "RandomBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "RandomBucket"
            - "/*"

  environment:
    BUCKET_NAME: { "Ref" : "RandomBucket" }

functions:
  hello-128:
    handler: handler.hello
    memorySize: 128
    environment:
      MEMORY: 128
    events:
      - http:
          path: hello-128
          method: get
  hello-256:
    handler: handler.hello
    memorySize: 256
    environment:
      MEMORY: 256
    events:
      - http:
          path: hello-256
          method: get
  hello-512:
    handler: handler.hello
    memorySize: 512
    environment:
      MEMORY: 512
    events:
      - http:
          path: hello-512
          method: get
  hello-1024:
    handler: handler.hello
    memorySize: 1024
    environment:
      MEMORY: 1024
    events:
      - http:
          path: hello-1024
          method: get
  hello-1536:
    handler: handler.hello
    memorySize: 1536
    environment:
      MEMORY: 1536
    events:
      - http:
          path: hello-1536
          method: get

resources:
  Resources:
    RandomBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET_NAME}
        AccessControl: BucketOwnerFullControl
