#!/bin/bash

az functionapp config appsettings set \
 --resource-group serverless-azure-random-rg \
 --name serverless-azure-random \
 --settings \
   AZURE_STORAGE_CONNECTION_STRING="${AZURE_STORAGE_CONNECTION_STRING}" \
   AZURE_STORAGE_CONTAINER=${AZURE_STORAGE_CONTAINER} \
   AZURE_STORAGE_FILE_CONTAINER=${AZURE_STORAGE_FILE_CONTAINER}
