# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: cloud-functions-research

# Please ensure the serverless-openwhisk provider plugin is installed globally.
# $ npm install -g serverless-openwhisk
# ...before installing project dependencies to register this provider.
# $ npm install
provider:
  name: openwhisk
  timeout: 240

# you can add packaging information here
package:
 include:
   - bin/hello
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  hello-128:
    handler: handler.hello
    memory: 128
    events:
      - http: GET hello-128
  hello-256:
    handler: handler.hello
    memory: 256
    events:
      - http: GET hello-256
  hello-512:
    handler: handler.hello
    memory: 512
    events:
      - http: GET hello-512

#    Functions can be defined using sequences rather than referring
#    to a handler.
#    sequence:
#      - parse_input
#      - do_some_algorithm
#      - construct_output

#    The following are a few example events you can configure
#    Check the event documentation for details
#    events:
#      - http: GET /api/users/create
#      - trigger: trigger_name


# extend the framework using plugins listed here:
# https://github.com/serverless/plugins
plugins:
  - serverless-openwhisk

# you can define custom triggers and trigger feeds using the resources section.
#
#resources:
#  triggers:
#    my_trigger:
#      parameters:
#        hello: world
#    alarm_trigger:
#      parameters:
#        hello: world
#     feed: /whisk.system/alarms/alarm
#     feed_parameters:
#       cron: '*/8 * * * * *'
